"""add_missing_message_columns

Revision ID: 12475ef3abe4
Revises: f2c4fa4b3fb2
Create Date: 2026-07-26 12:41:36.547377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12475ef3abe4'
down_revision: Union[str, None] = 'f2c4fa4b3fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_type', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('audio_url', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('status', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('cultural_footnotes', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('tts_url', sa.String(), nullable=True))
    op.alter_column('messages', 'original_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'original_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'tts_url')
    op.drop_column('messages', 'cultural_footnotes')
    op.drop_column('messages', 'status')
    op.drop_column('messages', 'audio_url')
    op.drop_column('messages', 'message_type')
    # ### end Alembic commands ###
